# Go-Agent Yapılandırma Dosyası
# Bu dosyadan model adı ve ollama sunucu adresi gibi ayarlar okunur.
ollama:
  # Kullanılacak modelin adı
  model: "deepseek-r1:8b"
  # Ollama API sunucusunun adresi
  url: "http://localhost:11434/api/generate"
